### ISSUE TITLE
Do not add or display unstable and breaking if false

### ISSUE THREAD

**Issue by sfOmikron** [FACT-Finder/snage#109]
'snage create' currently adds the flags 'unstable' and 'breaking' to the templates even if they are false and the UI displays it accordingly.

'snage create' should add them only if set to true or the UI should not display them if set to false.

**Comment by tvrg** [comment]
The first fix is not to force a user of `snage create` to provide a value for optional boolean fields. That way he can just skip that field and it will neither occur in the note nor in the ui.

But you're right, we should also add a way to hide chips depending on the field value.

**Comment by tvrg** [comment]
As a second fix I suggest that we migrate the two fields `breaking` and `unstable` to one optional enum field `state` with two values `breaking` and `unstable`. Then the state of a note can either be `breaking`, `unstable` or nothing. That's more precise as a note with `breaking: true` and `unstable: true` probably doesn't make sense. Maybe we find a better name than `state` for the new field.
