### ISSUE TITLE
Add JSON-API for changelog formatting tool

### ISSUE THREAD

**Issue by thecodechemist99** [FACT-Finder/snage#160]
Please add a JSON-API for the changelog formatting tool. The API should return all results of a query, grouped by type, as JSON in the following format:
```json
{
    "h1-text": {
        "h2-text": {
            "content": [
                {
                    "type": "meta",
                    "raw": "meta data block"
                },
                {
                    "type": "text",
                    "raw": "content block (including inline code and styling related tags)"
                },
                {
                    "type": "heading",
                    "heading": "h3-text",
                    "content": [
                        {
                            "type": "meta",
                            "raw": "meta data block"
                        },
                        {
                            "type": "text",
                            "raw": "content block (including inline code and styling related tags)"
                        },
                        {
                            "type": "table",
                            "raw": "table section (including inline code and styling related tags)",
                        },
                        {
                            "type": "code",
                            "raw": "code block",
                        },
                    ]
                }
            ]
        }
    }
}
```
The keys in the first two hierarchy levels function as headings, with the first level being the type (from grouping), second the ticket headings.
The second and third level values consist from arrays with content blocks. Each content block has a type, being „meta“ (for ticket metadata (e. g. type, version, date, … – the issue is not required but can be included if convenient)), „text“ (for standard text blocks, including inline code and styling related tags), „code“ (for code blocks), „table“ (for table sections, including their formatting and again inline code or styling within the table) or „heading“ (for a third hierarchy level).
All blocks except heading blocks contain the block content as a „raw“ key with a string value. Heading blocks contain a „heading“ tag with the heading as string value as well as a „content“ key with the next hierarchy level array as value.

**Comment by jmattheis** [comment]
Hey there,

we already have a JSON-API which returns all notes for a given query.
It returns all information that is visible on the current ui.
`content` and `summary` are strings that may contain markdown.

If it's difficult to implement the grouping client side, we could add an additional API for this.

We rather not return a HTML like structure, as this limits the usability of this API for different clients.

Example:
```bash
$ http "https://changelog.snage.dev/note?query="

{
    "fieldOrder": [ "type", "issue", "audience", "components", "version", "date" ],
    "groupByFields": [ "type", "issue", "audience", "version", "date" ],
    "notes": [
        {
            "content": "You can lint all change log notes using:\n```bash\n$ snage lint\n```",
            "id": "21-lint.md",
            "links": [
                {
                    "href": "https://github.com/FACT-Finder/snage/issues/21",
                    "label": "GitHub#21"
                }
            ],
            "style": {
                "borderLeft": "10px solid #2ecc71"
            },
            "summary": "Add `snage lint` command",
            "valueStyles": {
                "type": {
                    "background": "#2ecc71"
                }
            },
            "values": {
                "audience": "user",
                "components": [
                    "cli"
                ],
                "date": "2020-04-23",
                "issue": "21",
                "type": "add",
                "version": "0.0.2"
            }
        },
        // ..
    ]
}

```

**Comment by thecodechemist99** [comment]
Hi,
thank you for the feedback! I've been told there was no api yet.
The grouping is no issue, the existing API works fine for my purpose.
