### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by jmattheis** [FACT-Finder/snage#57]

**Comment by sfOmikron** [comment]
- The type pill should be colored according to the type (e.g. add in green, fix in red, ...)
- There should be a help button beneath the search bar which explains the available operators and the syntax

**Comment by sfOmikron** [comment]
- Highlight unstable and breaking versions

**Comment by sfOmikron** [comment]
- Add blue header with 'provided by FACT-Finder' or similar
