### ISSUE TITLE
Notes without version might have to appear first

### ISSUE THREAD

**Issue by tvrg** [FACT-Finder/snage#76]
Notes without version are unreleased. They probably should appear first and should be marked as unreleased somehow. Maybe the git-version provider should provide pre-release versions for these notes.

**Comment by jmattheis** [comment]
This should be configurable on the field I guess. something like emptyFirst: true,false.

**Comment by tvrg** [comment]
Either that, or we use semver pre-release versions and take that into account when sorting semver fields. Or both.

**Comment by tvrg** [comment]
Already fixed.
